modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "endship_elytra_nuker"
version = "${version}"
displayName = "EndShipElytraNuker"
authors = "QPCrummer"
description = '''
Deletes Endship Elytras
'''
#logoFile = ""

[[dependencies.endship_elytra_nuker]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.endship_elytra_nuker]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.endship_elytra_nuker]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
